name = "your-project-name"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[build]
command = "pnpm run pages:build"

# R2 Bucket binding
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "discord"

# KV namespace for orders
[[kv_namespaces]]
binding = "ORDERS_KV"
id = "49c455bf9c6641638394f672ed0dfca0"

# Discord webhook binding using service bindings
[[services]]
binding = "DISCORD_WEBHOOK"
service = "discord-webhook"
environment = "production"

[vars]
NEXT_PUBLIC_BASE_URL = "https://hackysoft.xyz"

[triggers]
crons = []