name = "hackysoft"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[build]
command = "pnpm run pages:build"

# KV namespace for blog posts
[[kv_namespaces]]
binding = "assets"
id = "6cad3744e6654db595fbe1fd444efdae"

[vars]
NEXT_PUBLIC_BASE_URL = "https://hackysoft.xyz"
NEXT_PUBLIC_PRODUCTS = '''
{
  "account_backup": {
    "name": "Account Backup",
    "description": "Get all info from your discord account in a nice txt file",
    "price": 7.99
  },
  "linux_rooter": {
    "name": "Linux Rooter",
    "description": "Control all your discord hosting at once",
    "price": 37.99
  },
  "gen_token": {
    "name": "Gen Token",
    "description": "Mass token discord token",
    "price": 14.99
  }
}
'''

[triggers]
crons = []