name = "your-project-name"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[build]
command = "pnpm run pages:build"

# R2 Bucket binding
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "discord"

# KV namespace for orders
[[kv_namespaces]]
binding = "ORDERS_KV"
id = "49c455bf9c6641638394f672ed0dfca0"

[vars]
NEXT_PUBLIC_BASE_URL = "https://hackysoft.xyz"
NEXT_PUBLIC_PRODUCTS = '''
{
  "account_backup": {
    "name": "Account Backup",
    "description": "Get all info from your discord account in a nice txt file",
    "price": 7.99
  },
  "linux_rooter": {
    "name": "Linux Rooter",
    "description": "Control all your discord hosting at once",
    "price": 37.99
  },
  "gen_token": {
    "name": "Gen Token",
    "description": "Mass token discord token",
    "price": 14.99
  }
}
'''

[triggers]
crons = []